#!/bin/sh

# Return hypervisor name or match result if 'name' provided

name="$1"

if [[ $(cat /sys/hypervisor/type 2>/dev/null) == 'xen' ]]; then
    hypervisor="xen"

elif [ -e /sys/devices/virtual/misc/kvm ]; then
    hypervisor="kvm"
fi

if [ ! -z $hypervisor ]; then
    if [ -z "$name" ]; then
        echo "$hypervisor"
        exit 0
    fi
    if [ "$name" == "$hypervisor" ]; then
        exit 0
    fi
fi

exit 1
